apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: url-shortener
data:
  DATABASE_NAME: hackathon_db
  DATABASE_HOST: postgres-cluster-rw.url-shortener.svc.cluster.local
  DATABASE_PORT: "5432"
  DATABASE_USER: postgres
  REDIS_URL: redis://valkey.url-shortener.svc.cluster.local:6379/0
