apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: url-shortener
spec:
  instances: 3

  postgresql:
    parameters:
      shared_buffers: "256MB"
      max_connections: "200"

  enableSuperuserAccess: true
  superuserSecret:
    name: db-credentials

  bootstrap:
    initdb:
      database: hackathon_db
      owner: postgres
      secret:
        name: db-credentials

  storage:
    size: 5Gi

  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 2
